config/routes.rb
MyPages::Application.routes.draw do
  resources :projects
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match 'about_me' => 'projects#about', :as => 'about', via: :get
  match 'purpose' => 'projects#purpose', :as => 'purpose', via: :get
  
  root to: 'projects#purpose'
  
  match 'signin' => 'sessions#new', via: :get
  match 'signout' => 'sessions#destroy', via: :delete

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  default_scope { order("created_at ASC")}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def about
  end
  
  def purpose
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :status, :timeline, :todo, :link, :brief, :tool)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # GET /sign_in
  def new
    
  end
  
  # POST /sessions
  def create
    if params[:session][:password] = ENV["ADMIN_PASSWORD"]
      session[ENV["ADMIN"]] = true
      redirect_to projects_path
    else
      flash.now[:alert] = 'Invalid Password!'
      render action: 'new'
    end
  end

  # DELETE /signout
  def destroy
    reset_session
    redirect_to projects_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def admin?
    session[ENV["ADMIN"]]
  end
  
  # Check for admin
  def admin_user
    redirect_to root_path, alert: "You do not have permission to access that!" unless admin?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Project Pages</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="headline">
    <h1>Welcome to My Project Pages!</h1>
  </div>

  <div class="top_menu">|
    <%= link_to 'My Projects', projects_path %> |
    <%= link_to 'My Motivations', purpose_path %> |
    <%= link_to 'About Me', about_path %> |

    
  </div>
  
  <div class="general_layout">
    <p id="alert"><%= alert %></p>
    <p id="notice"><%= notice %></p>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ['Concept', 'In Development', "Complete"] %>
  </div>
  <div class="field">
    <%= f.label "Brief Description" %><br>
    <%= f.text_area :brief %>
  </div>
  <div class="field">
    <%= f.label "Full Description" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :tool %><br>
    <%= f.text_field :tool %>
  </div>
  <div class="field">
    <%= f.label :timeline %><br>
    <%= f.text_area :timeline %>
  </div>
  <div class="field">
    <%= f.label :todo %><br>
    <%= f.text_area :todo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/about.html.erb
<h2>A little about me...</h2>


<p>
  <center>
    <strong>Lili Yang</strong>
    <br>
    yanglili369@gmail.com
  </center>
</p>

<p>
  <strong>Education:</strong>
  <table>
    <tr>
      <td>Bachelor of Science, California Institute of Technology: <strong>(GPA: 4.0)</strong></td>
      <td class="left_text">June 2011</td>
    </tr>
  </table>
  Double Major: Applied and Computational Mathematics; Business, Economics, and Management
</p>

<p>
  <strong>Work Experience:</strong>
  <table>
    <tr>
      <td>Citigroup Inc - Quantitative Analyst Rotational Program</td>
      <td class="left_text">New York City, New York</td>
    </tr>
    <tr>
      <td>Credit Strategies Analyst</td>
      <td class="left_text">2012 - 2013</td>
    </tr>
  </table>
  <ul>
    <li>Contributed analysis towards the Speculative Grade Credit Weekly, High Yield Strategy Notes, and Leveraged Loan Strategy Notes publications.</li>
    <li>Assisted clients and Citi internal personnel with special data and analysis requests on topics including, but not limited to, ETFs, new issuance, fund flows, default rates, and credit indices.</li>
    <li>Developed models in excel and VBA geared towards a better understanding of and trade ideas generation in the IG and HY credit markets. Some examples: Short-dated Bond Monitor, On-the-Run Spread Report.</li>
  </ul>
</p>

<p>
  <table>
    <tr>
      <td>CMO Trader</td>
      <td class="left_text">2011 - 2012</td>
    </tr>
  </table>
  <ul>
    <li>Structured Collateralized Mortgage Obligations (CMO) products. Worked with accounts to finalize structures and pricing, and to execute the trades.</li>
    <li>Maintained a book of mortgage pools. Duties included bidding on select pool lists, marking to market, maintaining hedges, and allocating pools towards CMO creation. Built an excel tool specifically for this purpose.</li>
    <li>Assisted with the day to day operations of the desk. Worked together frequently with clients, sales, risk control, back office, and technology.</li>
  </ul>
</p>

<p>
  <table>
    <tr>
      <td>CIGNA</td>
      <td class="left_text">Bloomfield, Connecticut</td>
    </tr>
    <tr>
      <td>Actuarial Intern</td>
      <td class="left_text">June - Aug 2010</td>
    </tr>
  </table>
  <ul>
    <li>Tweaked mortality assumptions and assessed reserves for CIGNA’s settlement annuity product</li>
    <li>Automated cash value illustration spreadsheets in excel for CIGNA’s corporate-owned life insurance products</li>
  </ul>
</p>

<p>
  <table>
    <tr>
      <td>Summer Undergraduate Research Fellowship, CIT</td>
      <td class="left_text">Pasadena, California</td>
    </tr>
    <tr>
      <td>Advisor: Professor Leeat Yariv</td>
      <td class="left_text">June - Sept 2009</td>
    </tr>
  </table>
  <ul>
    <li>Examined the influence of the “snowball effect” on US primary elections</li>
  </ul>
</p>

<p>
  <table>
    <tr>
      <td>Advisor: Professor Philip T. Hoffman</td>
      <td class="left_text">June - Sept 2008</td>
    </tr>
  </table>
  <ul>
    <li>Quantitatively explored economic and geopolitical theories as possible explanations for historical nation size.</li>
  </ul>
</p>

<p>
  <strong>Society of Actuary Exams:</strong><br>
  Exam P - Probability; Exam FM - Financial Mathematics
</p>

<p>
  <strong>Computer Skills:</strong><br>
  Microsoft Excel, Microsoft Access, VBA, Mathematica, Matlab, Python, Ruby on Rails
</p>

<p>
  <strong>Other Language Skills:</strong><br>
  Chinese - fluent native speaker; Spanish - intermediate level
</p>

<p>
  <strong>Activities and Interests:</strong>
  <table>
    <tr>
      <td>Caltech Varsity Tennis Team</td>
      <td class="left_text">2007 - 2010</td>
    </tr>
    <tr>
      <td>Classical Piano, solo and ensemble</td>
      <td class="left_text">1998 - Present</td>
    </tr>
    <tr>
      <td>Caltech Freshman Admissions Committee</td>
      <td class="left_text">2008 - 2010</td>
    </tr>
  </table>
  <ul>
    <li>Responsible for reading freshman applications to Caltech and recommending decisions</li>
  </ul>
  <table>
    <tr>
      <td>ASCIT Social Team Member</td>
      <td class="left_text">2007 - 2009</td>
    </tr>
  </table>
  <ul>
    <li>Organized social events for the entire student body of Caltech</li>
  </ul>
  <table>
    <tr>
      <td>Prefrosh Weekend Representative</td>
      <td class="left_text">2008 - 2010</td>
    </tr>
  </table>
  <ul>
    <li>Organized Caltech introductory weekend for prospective freshmen</li>
  </ul>
</p>

app/views/projects/edit.html.erb
<h2>Editing Project</h2>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h2>Listing Current Projects</h2>

<div class="project_list">
<% @projects.each do |project| %>

  <h3><%= link_to project.title, project_path(project)%></h3>
  
  <p>
    <strong>Brief Description: </strong>
    <%= simple_format(project.brief) %>
  </p>  
  <% unless project.link.blank? %>
  <p>
    <strong>
      Find the website <%= link_to 'HERE', project.link %>
    </strong>
  </p>
  <% end %>
  <p>
    <strong>Status: </strong>
    <%= project.status %>
  </p>
  
  <% if admin? %>
  <p>|
    <%= link_to 'Show', project %> |
    <%= link_to 'Edit', edit_project_path(project) %> |
    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %> |
  </p>
  
  <% end %>
  
  <hr>

<% end %>
</div>

<br>

<% if admin? %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

<br><br><br><br><br>
<small>
  <% if admin? %>
    <%= link_to "Sign Out", signout_path, method: "delete" %>
  <% else %>
    <%= link_to "Sign In", signin_path %>
  <% end %>
</small>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/purpose.html.erb
<h2>So what's this all about?</h2>

<p>
    I've been interested in computers and computer programming for a very long time. It is a fascinating and dynamic field of knowledge and is becoming ever more essential to our day to day living. Recently, I've taken a more active interest in learning how to program. I've created this website to keep track of projects that I have been, and will be working on in furtherance of along the way.
</p>

<p>
    This isn't just intended to be a record of my achievements. It's also meant to be a log of the things that I learn along the way. And perhaps, sometime soon, it'll be a way for me to solicit comments and suggestions from others on the web. It is also my hopes that others will find my journey informative.
</p>

<p>
  So without further ado, on to the 
  <%= link_to 'projects...', projects_path %>
</p>

app/views/projects/show.html.erb
<h2><%= @project.title %></h2>

<p>
  <strong>Description:</strong>
  <%= simple_format(@project.description) %>
</p>

<% unless @project.link.blank? %>
<p>
  <strong>
    Find the website <%= link_to 'HERE', @project.link %>
  </strong>
</p>
<% end %>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>
<p>
  <strong>Timeline:</strong>
  <%= simple_format(@project.timeline) %>
</p>
<p>
  <strong>Things to Come:</strong>
  <%= simple_format(@project.todo) %>
</p>


<%= link_to 'Back to Projects', projects_path %>